---
title: "pupil-analysis-pcacleaned"
output: html_document
date: "2024-08-12"
---

```{r}
library(dplyr)
library(readr)
library(ggplot2)
library(tidyverse)
library(patchwork)
library(lme4)
library(lmerTest)
library(sjPlot)
library(ggeffects)
library(MuMIn)

theme_set(theme_bw() + #set the theme 
            theme(text = element_text(family = "Helvetica",size = 10))) #set the default text size
purpleOrange_palette6 = c("purple4","purple2","plum3","khaki","gold","goldenrod4")
purpleOrange_palette2 = c("purple4","gold")
size_palette2 = c("#e78ac3","#66c2a5")
```

```{r}
anticipation_window = c(2+2,4+2) #3-4 NOT plus 1.5 seconds of delay
outcome_window_ant = c(14,16) #NOT plus 1.5 seconds of delay
outcome_window_out = c(6,8) #NOT plus 1.5 seconds of delay
```

```{r}
sr = 200

df.pupil <- read_csv("./esther/pupil_cleaned.csv") %>% 
  mutate(cue_value = factor(cue_value, levels = c("-$5","-$1","-$0","+$0","+$1","+$5"))) %>% 
  filter(!is.na(subject)) %>% 
  rename(pupilDiameter_scaled = cleaned_pupilDiameter)
  

bad_participants <- read_delim("../subject_to_drop_pupil.txt", col_names = F, delim = " ")

df.pupil <- df.pupil %>% 
  filter(!subject %in% bad_participants) %>% 
  filter(!subject %in% c("sk240301","hc240324","js240311","jy240308","tc240311","el240312"))

ggpubr::ggdensity(df.pupil$pupilDiameter_scaled)

unique(df.pupil$subject)
length(unique(df.pupil$subject))
unique(df.pupil$trial)
names(df.pupil)

df.pupil$cue_value <- factor(df.pupil$cue_value,
                                levels = c("-$5","-$1","-$0","+$0","+$1","+$5"))

df.pupil$arousal <- df.pupil$arating
df.pupil$valence <- df.pupil$vrating

df.pupil <- df.pupil %>% 
  ungroup()%>%
  group_by(subject) %>% 
  mutate(arousal_scaled = as.numeric(scale(arousal)),
         valence_scaled = as.numeric(scale(valence)))

ggplot(df.pupil %>% 
         filter(sample_in_trial_t >= 0) %>% 
         group_by(subject,sample_in_trial_t) %>% 
         summarise(pupilDiameter_scaled = mean(pupilDiameter_scaled, na.rm = T)))+
  geom_line(aes(x = sample_in_trial_t, y = pupilDiameter_scaled,
                 color = subject),size = 1)+
  scale_x_continuous(breaks = 0:22)+
  theme(legend.position = "none")
```



# by cue size

```{r}
df.pupil_summary_bc_size <- df.pupil%>%
  filter(sample_in_trial_t <= anticipation_window[2]+1.5,
         sample_in_trial_t >= 0) %>% 
  mutate(pupilDiameter_scaled = as.numeric(scale(pupilDiameter_scaled))) %>%
  ungroup()%>%
  mutate(cue_size = factor(cue_size, labels = c("small","large"))) %>% 
  group_by(cue_size,sample_in_trial_t,subject)%>%
  summarise(pupilDiameter_scaled = mean(pupilDiameter_scaled, na.rm = T)) %>% 
  group_by(cue_size,sample_in_trial_t) %>% 
  summarise(mean = mean(pupilDiameter_scaled, na.rm = T),
            se = sd(pupilDiameter_scaled, na.rm = T)/n())

ggplot(df.pupil_summary_bc_size %>% 
         filter(!is.na(cue_size)), aes(x = sample_in_trial_t,
                       y = mean))+
  geom_line(aes(color = cue_size), size = 1)+
  geom_ribbon(aes(x = sample_in_trial_t,
                  ymin = mean-se, 
                  ymax = mean+se, fill = cue_size), 
              alpha = 0.3)+
  scale_color_manual(values = size_palette2)+
  scale_fill_manual(values = size_palette2)+
  annotate("rect", xmin =0.1, xmax = 2, ymin = -2.5, ymax = 1.5,
           color = "lightseagreen", fill = NA)+
  annotate("text", x = 1,y = 1.2, label = "anticipation",
          color = "lightseagreen")+
    annotate("rect", xmin =2.1, xmax = 4, ymin = -2.5, ymax = 1.5,
          color = "lightskyblue1", fill = NA)+
  annotate("text", x = 3,y = 1.2, label = "fixation",
          color = "lightskyblue1")+
  labs(title = "anticipation phase",
       x = "time (s)",
       y = "z-scored pupil size")+
  theme(legend.position = "none")+
  ylim(-2.5,1.5)

```

# by cue value
```{r}
df.pupil_summary_bc_values_all1 <- df.pupil%>%
  mutate(pupilDiameter_scaled = as.numeric(scale(pupilDiameter_scaled))) %>% 
  filter(probe == 1) %>% 
  ungroup()%>%
  filter(!is.na(cue_value)) %>% 
  group_by(cue_value,sample_in_trial_t)%>%
  summarise(mean = mean(pupilDiameter_scaled, na.rm = T))

ggplot(df.pupil_summary_bc_values_all1 %>% 
         filter(sample_in_trial_t >= 0,sample_in_trial_t <= 20), aes(x = sample_in_trial_t,
                       y = mean))+
  geom_line(aes(color = cue_value), size = 1)+
  scale_color_manual(values = purpleOrange_palette6)+
  scale_fill_manual(values = purpleOrange_palette6)+
  annotate("rect", xmin =0.1, xmax = 2, ymin = -1.5, ymax = 1.5,
           color = "lightseagreen", fill = NA)+
  annotate("text", x = 1,y = 1.2, label = "anticipation",
          color = "lightseagreen")+
    annotate("rect", xmin =2.1, xmax = 4, ymin = -1.5, ymax = 1.5,
          color = "lightskyblue1", fill = NA)+
  annotate("text", x = 3,y = 1.2, label = "fixation",
          color = "lightskyblue1")+
  annotate("rect", xmin =12.1, xmax = 14, ymin = -1.5, ymax = 1.5,
          color = "lightskyblue1", fill = NA)+
  annotate("text", x = 13,y = 1.2, label = "fixation",
          color = "lightskyblue1")+
  annotate("rect", xmin =14.1, xmax = 16, ymin = -1.5, ymax = 1.5,
           color = "lightskyblue3", fill = NA)+
  annotate("text", x = 15,y = 1.2, label = "target",
          color = "lightskyblue3")+
  annotate("rect", xmin = 16.1, xmax = 18, ymin = -1.5, ymax = 1.5,
           color = "lightskyblue4", fill = NA)+
  annotate("text", x = 17,y = 1.2, label = "outcome",
          color = "lightskyblue4")+
  labs(title = "anticipation probes",
       x = "time (s)",
       y = "z-scored pupil size")

df.pupil_summary_bc_values_all2 <- df.pupil%>%
  mutate(pupilDiameter_scaled = as.numeric(scale(pupilDiameter_scaled))) %>% 
  filter(probe == 2) %>% 
  ungroup()%>%
  filter(!is.na(cue_value)) %>% 
  group_by(cue_value,sample_in_trial_t)%>%
  summarise(mean = mean(pupilDiameter_scaled, na.rm = T))

ggplot(df.pupil_summary_bc_values_all2 %>% 
         filter(sample_in_trial_t >= 0,sample_in_trial_t <= 18), aes(x = sample_in_trial_t,
                       y = mean))+
  geom_line(aes(color = cue_value), size = 1)+
  scale_color_manual(values = purpleOrange_palette6)+
  scale_fill_manual(values = purpleOrange_palette6)+
  annotate("rect", xmin =0.1, xmax = 2, ymin = -1.5, ymax = 1.5,
           color = "lightseagreen", fill = NA)+
  annotate("text", x = 1,y = 1.2, label = "anticipation",
          color = "lightseagreen")+
  annotate("rect", xmin =2.1, xmax = 4, ymin = -1.5, ymax = 1.5,
          color = "lightskyblue1", fill = NA)+
  annotate("text", x = 3,y = 1.2, label = "fixation",
          color = "lightskyblue1")+
  annotate("rect", xmin =4.1, xmax = 6, ymin = -1.5, ymax = 1.5,
           color = "lightskyblue3", fill = NA)+
  annotate("text", x = 5,y = 1.2, label = "target",
          color = "lightskyblue3")+
  annotate("rect", xmin = 6.1, xmax = 8, ymin = -1.5, ymax = 1.5,
           color = "lightskyblue4", fill = NA)+
  annotate("text", x = 7,y = 1.2, label = "outcome",
          color = "lightskyblue4")+
  labs(title = "outcome probes",
       x = "time (s)",
       y = "z-scored pupil size")
```

```{r}
df.pupil_summary_anti <- df.pupil%>%
  filter(sample_in_trial_t <= anticipation_window[2]+1.5,
         sample_in_trial_t >= 0)%>%
  ungroup()%>%
  group_by(subject) %>% 
  mutate(pupilDiameter_scaled = as.numeric(scale(pupilDiameter_scaled))) %>% 
  group_by(cue_value,sample_in_trial_t)%>%
  summarise(mean = mean(pupilDiameter_scaled, na.rm = T),
            lower = mean(pupilDiameter_scaled, na.rm = T) - qt(0.975, df = n() - 1) * sd(pupilDiameter_scaled, na.rm = T) / sqrt(n()),
            upper = mean(pupilDiameter_scaled, na.rm = T) + qt(0.975, df = n() - 1) * sd(pupilDiameter_scaled, na.rm = T) / sqrt(n()))

ggplot(df.pupil_summary_anti, aes(x = sample_in_trial_t,
                       y = mean))+
  geom_line(aes(color = cue_value), size = 1)+
  geom_ribbon(aes(x = sample_in_trial_t,
                  ymin = lower,
                  ymax = upper, fill = cue_value),
              alpha = 0.3)+
  scale_color_manual(values = purpleOrange_palette6)+
  scale_fill_manual(values = purpleOrange_palette6)+
  annotate("rect", xmin =0.1, xmax = 2, ymin = -1.5, ymax = 1.5,
           color = "lightseagreen", fill = NA)+
  annotate("text", x = 1,y = 1.2, label = "anticipation",
          color = "lightseagreen")+
  annotate("rect", xmin =2.1, xmax = 4, ymin = -1.5, ymax = 1.5,
          color = "lightskyblue1", fill = NA)+
  annotate("text", x = 3,y = 1.2, label = "fixation",
          color = "lightskyblue1")+
  theme(legend.position = "none")+
  labs(title = "anticipation phase (N = 28)",
       x = "time (s)",
       y = "z-scored pupil size")

ggsave("../../../VRMID-analysis/figures/study3_fig1_ant_cleaned.png",width = 4, height = 5, units = "in",dpi = 300)
```

# confirmatory


```{r warning = F, message = F}
data_lm_anti <-  df.pupil%>%
  filter(!subject %in% c("tc240311","st240312")) %>% 
  mutate(pupil_window = ifelse(sample_in_trial_t <= outcome_window_ant[2] & 
                                 sample_in_trial_t > outcome_window_ant[1],
                               "out",
                               ifelse(sample_in_trial_t <= anticipation_window[2] & 
                                        sample_in_trial_t > anticipation_window[1],
                                      "ant",NA)))%>%
  filter(probe == 1, pupil_window %in% c("out","ant"))%>%
  ungroup()%>%
  group_by(subject) %>% 
  mutate(arousal_scaled = as.numeric(scale(arousal)),
         valence_scaled = as.numeric(scale(valence)))%>% 
  group_by(probe,subject,trial,hit,cue_value,
           arousal,valence,pupil_window,
           arousal_scaled,valence_scaled,cue_size,rt,iti,last_iti)%>%
  summarise(mean_pupil_nobc_scaled= mean(pupilDiameter_scaled, na.rm = T))%>%
  pivot_wider(values_from = mean_pupil_nobc_scaled, names_from = pupil_window, names_prefix = "mean_pupil_nobc_scaled_")%>%
  ungroup()%>%
  group_by(subject)%>%
  mutate(log_rt = log(rt),
         log_rt = as.numeric(scale(log_rt)))

data_lm_outcome <-  df.pupil%>%
    filter(!subject %in% c("tc240311","st240312")) %>% 
  mutate(pupil_window = ifelse(probe == 2 & sample_in_trial_t <= outcome_window_out[2] 
                               & sample_in_trial_t > outcome_window_out[1],
                               "out",
                               ifelse(probe == 2 &  sample_in_trial_t <= anticipation_window[2] 
                                      & sample_in_trial_t > anticipation_window[1],
                                      "ant",NA)))%>%
  filter(probe == 2, pupil_window %in% c("out","ant"))%>%
  ungroup()%>%
  group_by(subject) %>% 
  mutate(arousal_scaled = as.numeric(scale(arousal)),
         valence_scaled = as.numeric(scale(valence)))%>% 
  group_by(probe,subject,trial,hit,cue_value,
           arousal,valence,pupil_window,
           arousal_scaled,valence_scaled,cue_size,rt,iti,last_iti)%>%
  summarise(mean_pupil_nobc_scaled= mean(pupilDiameter_scaled, na.rm = T))%>%
  pivot_wider(values_from = mean_pupil_nobc_scaled, names_from = pupil_window, names_prefix = "mean_pupil_nobc_scaled_")%>%
  ungroup()%>%
  group_by(subject)%>%
  mutate(log_rt = log(rt),
         log_rt = as.numeric(scale(log_rt)))
```

```{r}
modA <- lmer(mean_pupil_nobc_scaled_ant ~ cue_value + (1|cue_size) + (1|subject) + (1|last_iti),data_lm_anti)
mydf <- ggpredict(modA, terms = c("cue_value"))

ind_pupil_ant_sub <- df.pupil%>%
  filter(probe == 1,
         sample_in_trial_t > anticipation_window[1] & sample_in_trial_t <= anticipation_window[2])%>%
  ungroup()%>%
  group_by(subject,cue_value)%>%
  summarise(mean_pupil = mean(pupilDiameter_scaled, na.rm = T))

ggplot()+
  scale_color_manual(values = purpleOrange_palette6)+
  geom_jitter(data = ind_pupil_ant_sub, aes(x = cue_value, y = mean_pupil, group = subject),
              alpha = 0.3,width = 0.2)+
  geom_point(data = mydf, aes(x = x, y = predicted, color = x),
             size = 2)+
  geom_errorbar(data = mydf, aes(x = x, ymin = predicted-std.error, ymax = predicted+std.error,color = x),
                width = 0.2, size = 1)+
  labs(title = "Anticipation (1.5~3.5s \
       post fixation onset)")+
  theme(legend.position = "none")
```

```{r}
lme1 <- lmer(arousal_scaled ~ mean_pupil_nobc_scaled_ant + (1|subject) + (1|cue_size) + (1|last_iti),
              data_lm_anti)
summary(lme1)


lme1a <- lmer(scale(arousal_scaled) ~ scale(mean_pupil_nobc_scaled_ant) + (1|subject) + (1|cue_size) + (1|last_iti),
              data_lm_anti)
summary(lme1a)
EMAtools::lme.dscore(lme1, data = data_lm_anti,
                     type = "lme4")

lme2 <- lmer(scale(valence_scaled) ~ scale(mean_pupil_nobc_scaled_ant) + (1|subject) + (1|cue_size) + (1|last_iti),
              data_lm_anti)
summary(lme2)


p1a <- plot_model(lme1, type = "pred", terms = c("mean_pupil_nobc_scaled_ant"),
           show.data = T, dot.size = 0.5)+
  labs(title = "Anticipation arousal",
       x = "phasic pupil size",
       y = "scaled arousal")+
  scale_color_manual(values = purpleOrange_palette6)+
  scale_fill_manual(values = purpleOrange_palette6)


lme2 <- lmer(valence_scaled ~ mean_pupil_nobc_scaled_ant + (1|subject) + (1|cue_size) + (1|last_iti),
              data_lm_anti)
summary(lme2)
summary(lmer(scale(valence_scaled) ~ scale(mean_pupil_nobc_scaled_ant) + (1|subject) + (1|cue_size) + (1|last_iti),
              data_lm_anti))
p1b <- plot_model(lme2, type = "pred", terms = c("mean_pupil_nobc_scaled_ant"),
           show.data = T,dot.size = 0.5)+
  labs(title = "Anticipation valence",
       x = "phasic pupil size",
       y = "scaled valence")+
  xlim(-4,4)+
  scale_color_manual(values = purpleOrange_palette6)+
  scale_fill_manual(values = purpleOrange_palette6)

p1a+p1b

tp <- lmer(arousal_scaled ~  mean_pupil_nobc_scaled_ant +(1|subject) + (1|cue_size) + (1|last_iti),
              data_lm_anti)
round(r.squaredGLMM(tp)*100,2)
```

```{r}
ind_pupil_out_sub <- df.pupil%>%
  filter(ifelse(probe == 1, sample_in_trial_t <= outcome_window_ant[2] & sample_in_trial_t >
                  outcome_window_ant[1],
                sample_in_trial_t <= outcome_window_out[2] & sample_in_trial_t > outcome_window_out[1]))%>%
  ungroup()%>%
  group_by(subject,cue_value)%>%
  summarise(mean_pupil = mean(pupilDiameter_scaled, na.rm = T))

modO <- lmer(mean_pupil_nobc_scaled_out ~ cue_value * hit + (1|subject) + (1|cue_size) + (1|last_iti),data_lm_outcome)
anova(modO)
summary(modO)
mydf2 <- ggeffects::ggpredict(modO, terms = c("cue_value","hit")) %>% rename(hit = group)

ggplot()+
  # geom_jitter(data = ind_pupil_out_sub, aes(group = subject,
  #                                        x = cue_value, 
  #                                        y = mean_pupil),
  #           alpha = 0.1, width = 0.2)+
  geom_point(data = mydf2, aes(x = x, y = predicted,color = x, shape = hit),position = position_dodge(width = 0.50),
             size = 2)+
  geom_errorbar(data = mydf2, aes(x = x, ymin = predicted-std.error,
                                  ymax = predicted+std.error,color = x,
                                  linetype = hit),position = position_dodge(width = 0.50),
                size = 1, width = 0.2)+
  labs(title = "Outcome (1.5~3.5s after outcome onset)")+
  theme(legend.position = "right")+
  guides(color = FALSE)+
  scale_color_manual(values = purpleOrange_palette6)

```

```{r}
lme1 <- lmer(arousal_scaled ~ mean_pupil_nobc_scaled_out + (1|subject) + (1|cue_size) + (1|last_iti),
              data_lm_outcome)
summary(lme1)


lme1a <- lmer(scale(arousal_scaled) ~ scale(mean_pupil_nobc_scaled_out) + (1|subject) + (1|cue_size) + (1|last_iti),
              data_lm_outcome)
summary(lme1a)
EMAtools::lme.dscore(lme1, data = data_lm_outcome,
                     type = "lme4")

lme2 <- lmer(scale(valence_scaled) ~ scale(mean_pupil_nobc_scaled_out) + (1|subject) + (1|cue_size) + (1|last_iti),
              data_lm_anti)
summary(lme2)


p1a <- plot_model(lme1, type = "pred", terms = c("mean_pupil_nobc_scaled_out"),
           show.data = T, dot.size = 0.5)+
  labs(title = "Outcome arousal",
       x = "phasic pupil size",
       y = "scaled arousal")+
  scale_color_manual(values = purpleOrange_palette6)+
  scale_fill_manual(values = purpleOrange_palette6)


lme2 <- lmer(valence_scaled ~ mean_pupil_nobc_scaled_out + (1|subject) + (1|cue_size) + (1|last_iti),
              data_lm_outcome)
summary(lme2)
summary(lmer(scale(valence_scaled) ~ scale(mean_pupil_nobc_scaled_out) + (1|subject) + (1|cue_size) + (1|last_iti),
              data_lm_outcome))
p1b <- plot_model(lme2, type = "pred", terms = c("mean_pupil_nobc_scaled_out"),
           show.data = T,dot.size = 0.5)+
  labs(title = "Outcome valence",
       x = "phasic pupil size",
       y = "scaled valence")+
  xlim(-4,4)+
  scale_color_manual(values = purpleOrange_palette6)+
  scale_fill_manual(values = purpleOrange_palette6)

p1a+p1b

tp <- lmer(arousal_scaled ~  mean_pupil_nobc_scaled_out +(1|subject) + (1|cue_size) + (1|last_iti),
              data_lm_outcome)
round(r.squaredGLMM(tp)*100,2)
```


# rotation
# full signal
```{r message = F, warning=F}
nbins = 360
angles = seq(0,pi/2, by = pi/(2*nbins))
angles = data.frame(angle1d = angles*180/pi,
                    angle1r = angles,
                    sin1 = sin(angles),
                    cos1 = cos(angles))

angles <- angles%>%
  mutate(angle2d = angle1d + 90,
         angle2r = angle1r + pi/2,
         sin2 = sin(angle2r),
         cos2 = cos(angle2r))

lmer_out1 <- {}

for (i in 1:nrow(angles)){
  angle_info = angles[i,]
  data_lm_anti_temp <- data_lm_anti%>%
    mutate(axis1 = valence_scaled * angle_info$cos1 + arousal_scaled * angle_info$sin1,
           axis2 = valence_scaled * angle_info$cos2 + arousal_scaled * angle_info$sin2)
  sum_temp1 <- summary(lmer(scale(axis1) ~ scale(mean_pupil_nobc_scaled_ant) + (1|subject) + (1|cue_size) + (1|last_iti),
              data_lm_anti_temp))
  sum_temp2 <- summary(lmer(scale(axis2) ~ scale(mean_pupil_nobc_scaled_ant) + (1|subject) + (1|cue_size) + (1|last_iti),
              data_lm_anti_temp))
  lmer_out1 <- rbind(lmer_out1, sum_temp1$coefficients[2,],sum_temp2$coefficients[2,])
}

lmer_out1 <- as.data.frame(lmer_out1)
lmer_out1$axis = rep(c("axis1","axis2"),nrow(angles))
  
lmer_out1[seq(1,nrow(angles)*2,by = 2),"angle"] = angles$angle1d
lmer_out1[seq(2,nrow(angles)*2,by = 2),"angle"] = angles$angle2d

lmer_out1[seq(1,nrow(angles)*2,by = 2),"sin"] = angles$sin1
lmer_out1[seq(2,nrow(angles)*2,by = 2),"sin"] = angles$sin2

lmer_out1[seq(1,nrow(angles)*2,by = 2),"cos"] = angles$cos1
lmer_out1[seq(2,nrow(angles)*2,by = 2),"cos"] = angles$cos2

lmer_out1$p_val <- (lmer_out1$`Pr(>|t|)` < 0.001)

ggplot(lmer_out1, aes(x = angle,
                     y = Estimate))+
  geom_point(aes(color = p_val,
                 group = axis))+
  facet_wrap(~axis)+
  geom_hline(yintercept = 0)+
  labs(title = "Affect dimension ~ anticipatory pupil dilation",
       subtitle = "angle is between the axis and valence",
       color = "p < .001")+
  scale_color_manual(values = c("grey","maroon"))+
  geom_vline(xintercept = 90, linetype = "dashed")

a1f <- lmer_out1[which.max(abs(lmer_out1$Estimate)),]
```


```{r}
lmer_out2 <- {}

for (i in 1:nrow(angles)){
  angle_info = angles[i,]
  data_lm_out_temp <- data_lm_outcome%>%
    mutate(axis1 = valence_scaled * angle_info$cos1 + arousal_scaled * angle_info$sin1,
           axis2 = valence_scaled * angle_info$cos2 + arousal_scaled * angle_info$sin2)
  sum_temp1 <- summary(lmer(scale(axis1) ~ scale(mean_pupil_nobc_scaled_out) + (1|subject) + (1|cue_size) + (1|last_iti),
              data_lm_out_temp))
  sum_temp2 <- summary(lmer(scale(axis2) ~ scale(mean_pupil_nobc_scaled_out) + (1|subject) + (1|cue_size) + (1|last_iti),
              data_lm_out_temp))
  lmer_out2 <- rbind(lmer_out2, sum_temp1$coefficients[2,],sum_temp2$coefficients[2,])
}

lmer_out2 <- as.data.frame(lmer_out2)
lmer_out2$axis = rep(c("axis1","axis2"),nrow(angles))
  
lmer_out2[seq(1,nrow(angles)*2,by = 2),"angle"] = angles$angle1d
lmer_out2[seq(2,nrow(angles)*2,by = 2),"angle"] = angles$angle2d

lmer_out2[seq(1,nrow(angles)*2,by = 2),"sin"] = angles$sin1
lmer_out2[seq(2,nrow(angles)*2,by = 2),"sin"] = angles$sin2

lmer_out2[seq(1,nrow(angles)*2,by = 2),"cos"] = angles$cos1
lmer_out2[seq(2,nrow(angles)*2,by = 2),"cos"] = angles$cos2

lmer_out2$p_val <- (lmer_out2$`Pr(>|t|)` < 0.001)

ggplot(lmer_out2, aes(x = angle,
                     y = Estimate))+
  geom_point(aes(color = p_val))+
  facet_wrap(~axis)+
  geom_hline(yintercept = 0)+
  labs(title = "Affect dimension ~ outcome pupil dilation",
       subtitle = "angle is between the axis and valence",
       color = "p < .001")+
  scale_color_manual(values = c("grey","maroon"))+
  geom_vline(xintercept = 90, linetype = "dashed")

a2f <- lmer_out2[which.max(abs(lmer_out2$Estimate)),]
```

```{r}
df_axes1 <- rbind(a1f,a2f)
df_axes1$condition <- c("anti","outcome")

df_axes1 <- df_axes1%>%
  mutate(rad = angle/180 *pi,
         cos = cos(rad),
         sin = sin(rad))
pb2 <- ggplot(df_axes1%>%
         mutate(cos = cos * abs(Estimate),
                sin = sin * abs(Estimate)))+
  geom_segment(aes(x = -0.2, y = 0,
                   xend = 0.2, yend = 0),
               size = 0.5, arrow = arrow(length = unit(0.03, "npc")),
               color = "black", linetype = "dashed")+
  geom_segment(aes(x = 0, y = -0.1,
                   xend = 0, yend = 0.4),
               size = 0.5, arrow = arrow(length = unit(0.03, "npc")),
               color = "black", linetype = "dashed")+
  geom_segment(aes(x = 0,y = 0,
                   xend = cos, yend = sin,
                   color = condition),
               size = 2, arrow = arrow(length = unit(0.03, "npc")))+
  geom_text(aes(x = cos * 1.2, y = sin * 1.1, color = condition, label = round(Estimate,2)),
            size = 5,check_overlap = F)+
  scale_color_manual(values = c("#1B9E77","#D95F02"))+
  xlim(-0.2,0.2)+
  ylim(-0.1,0.5)+
  labs(x = "valence",
       y = "arousal",
       title = "full signal")

pb2

ggsave("~/Desktop/VRMID-analysis/figures/study3_axisrot_cleaned.png",width = 5, height = 4, units = "in",dpi = 300)
```

# cluster test
```{r warning = F, message=F}
df.pupil <- df.pupil %>% 
  mutate(Time_sec = floor(sample_in_trial_t)+1) %>% 
  group_by(subject,trial,Time_sec) %>% 
  mutate(sample_in_sec = row_number()) %>% 
  ungroup()

regression_coefs_ant_nobc <- {}

for (t in 1:20) {
  coefs <- {}
  print(t)
  for (s in 1:sr){
  df_ant_temp <- df.pupil%>%
  filter(probe == 1,Time_sec == t, sample_in_sec == s)
  if (nrow(df_ant_temp) > 0){
    lm_ant_temp <- lmer(scale(arousal_scaled) ~ scale(pupilDiameter_scaled) + (1|subject) + (1|cue_size) + (1|last_iti),df_ant_temp)
  lm_out <- c(summary(lm_ant_temp)$coefficient[2,],"r2m" = r.squaredGLMM(lm_ant_temp)[1])
  coefs <- rbind(coefs,lm_out)
  }
  }
  
   coefs <- as.data.frame(coefs)%>%
    mutate(sample_in_sec = row_number(),
           Time_sec = t)
  rownames(coefs) <- NULL
  regression_coefs_ant_nobc <- rbind(regression_coefs_ant_nobc,coefs)
}

regression_coefs_ant_nobc <- regression_coefs_ant_nobc%>%
  mutate(sample_point = row_number(),
         p_val = (`Pr(>|t|)` < .001))
write_csv(regression_coefs_ant_nobc,"regression_coefs_ant_nobc_cleaned.csv")
regression_coefs_ant_nobc <- read_csv("regression_coefs_ant_nobc_cleaned.csv")
```

#get the peak of the raw signal
```{r}
sr = 200
regression_coefs_nobc_smoothed <- regression_coefs_ant_nobc %>% 
  mutate(smoothed_tval = zoo::rollmean(`t value`, k = sr/2, fill = NA))%>% 
  mutate(smoothed_r2 = zoo::rollmean(r2m, k = sr/2, fill = NA))%>% 
  mutate(smoothed_beta = zoo::rollmean(Estimate, k = sr/2, fill = NA))

pp1<-ggplot(regression_coefs_nobc_smoothed, aes(x = sample_point,y = smoothed_beta))+
   geom_line(aes(color = (smoothed_beta > 0.2), group = 1),
             size = 1)+
  scale_x_continuous(breaks = seq(0,sr*20,sr), labels =  0:20)+
  labs(x = "time (sec)",
       y =  "Correlation strength (beta)",
       title = "Anticipation probe raw signal (PCA-cleaned)")+
  scale_color_brewer(palette = "Set1")+
  theme(legend.position = "none")+
  geom_vline(xintercept = c(0, 2, 4, 12,14, 16,18)*sr, linetype = "dashed", color = "gray37") +
  annotate("text", x = 1*sr, y = 0, label = "cue") +
  annotate("text", x = 3*sr, y = 0, label = "fixation") +
  annotate("text", x = 8*sr, y = 0, label = "rating") +
  annotate("text", x = 13*sr, y = 0, label = "fixation2") +
  annotate("text", x = 15*sr, y = -0.05, label = "triang") +
  annotate("text", x = 17*sr, y = -0.05, label = "out")

pp1
```


```{r warning = F, message=F}
regression_coefs_out_nobc <- {}

for (t in 1:20) {
  coefs <- {}
  print(t)
  for (s in 1:sr){
  df_out_temp <- df.pupil%>%
  filter(probe == 2,Time_sec == t, sample_in_sec == s)
  
    if (nrow(df_out_temp) > 0){
        lm_out_temp <- lmer(scale(arousal_scaled) ~ scale(pupilDiameter_scaled) + (1|subject) + (1|cue_size) + (1|last_iti),df_out_temp)
        lm_out <- c(summary(lm_out_temp)$coefficient[2,],"r2m" = r.squaredGLMM(lm_out_temp)[1])
        coefs <- rbind(coefs,lm_out)
    }
  }
  coefs <- as.data.frame(coefs)%>%
    mutate(sample_in_sec = row_number(),
           Time_sec = t)
  rownames(coefs) <- NULL
  regression_coefs_out_nobc <- rbind(regression_coefs_out_nobc,coefs)
}

regression_coefs_out_nobc <- regression_coefs_out_nobc%>%
  mutate(sample_point = row_number(),
         p_val = (`Pr(>|t|)` < .001))

write.csv(regression_coefs_out_nobc, "regression_coefs_out_nobc_cleaned.csv")
regression_coefs_out_nobc <- read_csv("regression_coefs_out_nobc_cleaned.csv")
```


#get the peak of the raw signal
```{r}
regression_coefs_out_nobc_smoothed <- regression_coefs_out_nobc%>% 
  mutate(smoothed_tval = zoo::rollmean(`t value`, k = sr/2, fill = NA))%>% 
  mutate(smoothed_r2 = zoo::rollmean(r2m, k = sr/2, fill = NA))%>% 
  mutate(smoothed_beta = zoo::rollmean(Estimate, k = sr/2, fill = NA))

pp2<-ggplot(regression_coefs_out_nobc_smoothed, aes(x = sample_point,y = smoothed_beta))+
   geom_line(aes(color = (smoothed_beta > 0.2), group = 1),
             size = 1)+
  scale_x_continuous(breaks = seq(0,(sr*20),sr), labels =  0:20)+
  labs(x = "time (sec)",
       y =  "Correlation strength (beta)",
       title = "Outcome probe raw signal (PCA-cleaned)")+
  scale_color_brewer(palette = "Set1")+
  theme(legend.position = "none")+
  geom_vline(xintercept = c(0,2,4,6,8,16)*sr,
             linetype = "dashed",
             color = "gray37") +
  annotate("text",x = 1*sr, y = -0.05,label = "cue")+
  annotate("text",x = 3*sr, y = -0.05,label = "fixation")+
  annotate("text",x = 5*sr, y = -0.05,label = "triang")+
  annotate("text",x = 7*sr, y = -0.05,label = "out")+
  annotate("text",x = 13*sr, y = -0.05,label = "rating")

pp1/pp2
ggsave("../../figures/study3_corrpeaks_cleaned.png",width = 6, height = 10, units = "in",dpi = 300)
```



# permutation test

### helper functions
```{r}
get.adjacency.matrix <- function(x, threshold) {
  x <- ifelse(abs(x) > threshold, 1, 0)
  n <- length(x)
  adjacency_matrix <- matrix(0, n, n)
  for (i in 1:n) {
    for (j in (i+1):n) {
      if (x[i] == 1 & x[j] == 1) {
        adjacency_matrix[i,j] <- 1
        adjacency_matrix[j,i] <- 1
      }
    }
  }
  return(adjacency_matrix)
}
```

```{r}
# Define a function to calculate cluster-level p-values
get_cluster_p_values <- function(orig_cluster_size, num_permutations, t_values) {
  cluster_p_values <- numeric(length(orig_cluster_size))
  for (i in 1:num_permutations) {
    # permuted_t_values <- sign(runif(length(t_values), -1, 1)) * abs(t_values)
    permuted_t_values <- sample(t_values)
    permuted_adjacency_matrix <- (abs(permuted_t_values) > threshold)
    permuted_cluster <- get_cluster_sizes(permuted_adjacency_matrix, time)
    permuted_cluster_sizes <- permuted_cluster$cluster
    for (j in 1:length(orig_cluster_size)) {
      if (length(permuted_cluster_sizes) != 0){
        cluster_p_values[j] <- cluster_p_values[j] + (permuted_cluster_sizes >= orig_cluster_size[j])
      }
    }
  }
  cluster_p_values <- pmin(cluster_p_values / num_permutations, 1)
  return(cluster_p_values)
}
```

```{r}
# Define a function to calculate cluster sizes
get_cluster_sizes <- function(x,time) {
  cluster_indices <- cumsum(x)
  cluster_sizes <- tapply(cluster_indices, cluster_indices, length)
  cluster_sizes <- cluster_sizes[cluster_sizes >= cluster_extent_threshold & names(cluster_sizes) != 0]
  start_time <- c()
  end_time <- c()

  for (i in 1:length(cluster_sizes)){
    temp_time <- time[which(cluster_indices %in% names(cluster_sizes)[i])]
    start_time[i] <- min(temp_time)
    end_time[i] <- max(temp_time)
  }
  cluster_info <- list()
  cluster_info$cluster <- cluster_sizes
  cluster_info$start_time <- start_time
  cluster_info$end_time <- end_time
  return(cluster_info)
}
```

## anticipation, raw
```{r warning = F, message=F}
# Define your data: t-values and beta estimates for each time point
t_values <- regression_coefs_ant_nobc$`t value`
time <- regression_coefs_ant_nobc$sample_point
beta_estimates <- regression_coefs_ant_nobc$Estimate

# Define your cluster-forming threshold (e.g. t-value of 2.0)
threshold <- 2.096

t_values[1] = threshold - 0.1 #somehow the algorithm requires the first datapoint to be non-sig in order to form a cluster
# Define your cluster extent threshold (e.g. minimum number of adjacent time points)
cluster_extent_threshold <- sr*2

# Get the adjacency matrix based on cluster-forming threshold
adjacency_matrix <- abs(t_values) < threshold

  # View(cbind(cluster_indices,time,adjacency_matrix))

orig_cluster <- get_cluster_sizes(adjacency_matrix,time)
orig_cluster_size <- orig_cluster$cluster

num_permutations <- 1000
cluster_threshold <- 0.05

cluster_p_values <- get_cluster_p_values(orig_cluster_size, 
                                         num_permutations, 
                                         t_values)

orig_cluster$start_time/sr

for (c in 1:length(orig_cluster$cluster)) {
  start_time <- orig_cluster$start_time[c]
  end_time <- orig_cluster$end_time[c]
  cluster_size <- orig_cluster$cluster[c]
  print(paste("Cluster from", round(start_time/sr,2), "s to", round(end_time/sr,2), "s (", cluster_size, "time points) with p-value", cluster_p_values[c]))
}

d1a <- as.data.frame(cbind(orig_cluster$start_time,orig_cluster$end_time,cluster_p_values))
names(d1a)[1:2] <- c("Start","End")
d1a$Start/sr
d1a$End/sr
```


```{r}
ant_nobc_pupil <- df.pupil%>%
  filter(probe == 1)%>%
  mutate(cluster = ifelse(sample_in_trial_n>= d1a[1,1] & sample_in_trial_n <= d1a[1,2],
                          "ant",
                          ifelse(sample_in_trial_n>= d1a[2,1] & sample_in_trial_n <= d1a[2,2],
                          "out",NA)))%>%
  filter(cluster %in% c("ant","out"))%>%
  group_by(subject,probe,cluster,cue_size,trial,arousal_scaled,valence_scaled,last_iti)%>%
  summarise(mean_pupil = mean(pupilDiameter_scaled,
                                 na.rm = T))%>%
  pivot_wider(names_from = "cluster", values_from = "mean_pupil")

ant_nobc_pupil$axis <-  ant_nobc_pupil$arousal_scaled
summary(lmer(scale(axis)~ scale(ant)+ (1|subject) + (1|cue_size) + (1|last_iti),ant_nobc_pupil))
summary(l1<-lmer(scale(axis)~ scale(ant)+ scale(out)+ (1|subject) + (1|cue_size) + (1|last_iti),ant_nobc_pupil))

r.squaredGLMM(l1)*100
```



```{r}
df.pupil_summary_anticipation_collapse_r <- df.pupil%>%
  ungroup()%>%
  filter(probe == 1,sample_in_trial_n <= 20*sr)%>%
  group_by(sample_in_trial_n,sample_in_trial_t)%>%
  summarise(mean = mean(pupilDiameter_scaled, na.rm = T),
            lower = mean(pupilDiameter_scaled, na.rm = T) - qt(0.975, df = n() - 1) * sd(pupilDiameter_scaled, na.rm = T) / sqrt(n()),
            upper = mean(pupilDiameter_scaled, na.rm = T) + qt(0.975, df = n() - 1) * sd(pupilDiameter_scaled, na.rm = T) / sqrt(n()))%>%
  mutate(significant_cluster = ifelse(sample_in_trial_n >= d1a[1,1] & sample_in_trial_n <= d1a[1,2] |
                                        sample_in_trial_n >= d1a[2,1] & sample_in_trial_n <= d1a[2,2],"sig","ns"))

p1a <- ggplot(df.pupil_summary_anticipation_collapse_r%>%
         filter(sample_in_trial_t <= 18, sample_in_trial_t >= 0), aes(x = sample_in_trial_t,
                       y = mean))+
  geom_point(aes(color = significant_cluster),
             size = 0.5)+
  geom_ribbon(aes(x = sample_in_trial_t,
                  ymin = lower, 
                  ymax = upper), 
              alpha = 0.2)+
  theme(legend.position = "right")+
  scale_color_viridis_d()+
  annotate("rect", xmin =0.1, xmax = 2, ymin = -1.5, ymax = 1.5,
           color = "lightseagreen", fill = NA)+
  annotate("text", x = 1,y = 1.2, label = "c",
          color = "lightseagreen")+
  annotate("rect", xmin =2.1, xmax = 4, ymin = -1.5, ymax = 1.5,
          color = "lightskyblue1", fill = NA)+
  annotate("text", x = 3,y = 1.2, label = "f",
          color = "lightskyblue1")+
  annotate("rect", xmin =12.1, xmax = 14, ymin = -1.5, ymax = 1.5,
          color = "lightskyblue1", fill = NA)+
  annotate("text", x = 13,y = 1.2, label = "f",
          color = "lightskyblue1")+
  annotate("rect", xmin =14.1, xmax = 16, ymin = -1.5, ymax = 1.5,
           color = "lightskyblue3", fill = NA)+
  annotate("text", x = 15,y = 1.2, label = "t",
          color = "lightskyblue3")+
  annotate("rect", xmin = 16.1, xmax = 18, ymin = -1.5, ymax = 1.5,
           color = "lightskyblue4", fill = NA)+
  annotate("text", x = 17,y = 1.2, label = "o",
          color = "lightskyblue4")+
  # annotate("rect", xmin = 5.5, xmax = 7.5, ymin = -0.5, ymax = 0.5,
  #          color = "red", fill = "red", alpha = 0.1)+
  labs(title = "anticipation probe",
       subtitle = "significant cluster overlayed on raw pupil",
       x = "time (s)",
       y = "z-scored pupil size")+
  geom_segment(aes(x = 8, y = 1, xend = 8, yend = 0.7),
                  arrow = arrow(length = unit(0.03, "npc")))+
  annotate("text",x = 8,y=1.2,label = "arousal report")

p1a
```


```{r warning = F, message=F}
regression_coefs_out_nobc <- {}

for (t in 1:20) {
  coefs <- {}
  print(t)
  for (s in 1:sr){
  df_out_temp <- df.pupil%>%
  filter(probe == 2,Time_sec == t, sample_in_sec == s)
  
  if (nrow(df_out_temp) > 0) {
     df_out_temp <- lmer(scale(arousal_scaled) ~ scale(pupilDiameter_scaled) + (1|subject) + (1|cue_size) + (1|last_iti),df_out_temp)
    lm_out <- summary(df_out_temp)$coefficient[2,]
    coefs <- rbind(coefs,lm_out)
  }
  }
  coefs <- as.data.frame(coefs)%>%
    mutate(sample_in_sec = row_number(),
           Time_sec = t)
  rownames(coefs) <- NULL
  regression_coefs_out_nobc <- rbind(regression_coefs_out_nobc,coefs)
}

regression_coefs_out_nobc <- regression_coefs_out_nobc%>%
  mutate(sample_point = row_number(),
         p_val = (`Pr(>|t|)` < .001))

write.csv(regression_coefs_out_nobc, "regression_coefs_out_nobc.csv")
regression_coefs_out_nobc <- read_csv("regression_coefs_out_nobc.csv")
```


#get the peak of the raw signal
```{r}
regression_coefs_out_nobc_smoothed <- regression_coefs_out_nobc %>% 
  mutate(smoothed_tval = zoo::rollmean(`t value`, k = sr, fill = NA))

ggplot(regression_coefs_out_nobc_smoothed, aes(x = sample_point,y = smoothed_tval))+
  geom_point(aes(color = (`Pr(>|t|)` < 1/(sr*20))),
             size = 1)+
  annotate("rect", xmin = 5.5*sr, xmax = 7.5*sr, ymin = 1, ymax = 8,
           alpha = .2, color = "orange", fill = NA, linetype = "dashed")+
    annotate("rect", xmin =7.5*sr, xmax = 9.5*sr, ymin = 1, ymax = 8,
           alpha = .2, color = "violet", fill = NA, linetype = "dashed")+
  annotate("rect", xmin =9.5*sr, xmax = 11.5*sr, ymin = 1, ymax = 8,
           alpha = .2, color = "blue", fill = NA, linetype = "dashed")+
  scale_x_continuous(breaks = seq(0,(sr*20),sr), labels =  0:20)+
  labs(x = "time (sec)",
       y =  "Correlation strength (t value)",
       title = "Raw signal")+
  scale_color_brewer(palette = "Set1")+
  theme(legend.position = "none")
```

```{r warning = F, message=F}
# Define your data: t-values and beta estimates for each time point
t_values <- regression_coefs_out_nobc$`t value`
time <- regression_coefs_out_nobc$sample_point
beta_estimates <- regression_coefs_out_nobc$Estimate

# Define your cluster-forming threshold (e.g. t-value of 2.0)
threshold <- 2.096

# Define your cluster extent threshold (e.g. minimum number of adjacent time points)
cluster_extent_threshold <- sr*2

# Get the adjacency matrix based on cluster-forming threshold
adjacency_matrix <- abs(t_values) < threshold

  # View(cbind(cluster_indices,time,adjacency_matrix))

orig_cluster <- get_cluster_sizes(adjacency_matrix,time)
orig_cluster_size <- orig_cluster$cluster

num_permutations <- 1000
cluster_threshold <- 0.05

cluster_p_values <- get_cluster_p_values(orig_cluster_size, 
                                         num_permutations, 
                                         t_values)

orig_cluster$start_time/sr

for (c in 1:length(orig_cluster$cluster)) {
  start_time <- orig_cluster$start_time[c]
  end_time <- orig_cluster$end_time[c]
  cluster_size <- orig_cluster$cluster[c]
  print(paste("Cluster from", round(start_time/sr,2), "s to", round(end_time/sr,2), "s (", cluster_size, "time points) with p-value", cluster_p_values[c]))
}

d2a <- as.data.frame(cbind(orig_cluster$start_time,orig_cluster$end_time,cluster_p_values))
names(d2a)[1:2] <- c("Start","End")
d2a
d2a$Start/sr
d2a$End/sr

regression_coefs_out_nobc <- regression_coefs_out_nobc%>%
  mutate(significant_cluster = ifelse((sample_point >= d2a[1,1] & sample_point <= d2a[1,2]),"sig","ns"))
```



```{r}
df.pupil_summary_outcome_collapse_r<- df.pupil%>%
  ungroup()%>%
  filter(probe == 2,sample_in_trial_n <= 20*sr)%>%
  group_by(sample_in_trial_n,sample_in_trial_t)%>%
  summarise(mean = mean(pupilDiameter_scaled, na.rm = T),
            lower = mean(pupilDiameter_scaled, na.rm = T) - qt(0.975, df = n() - 1) * sd(pupilDiameter_scaled, na.rm = T) / sqrt(n()),
            upper = mean(pupilDiameter_scaled, na.rm = T) + qt(0.975, df = n() - 1) * sd(pupilDiameter_scaled, na.rm = T) / sqrt(n()))%>%
  mutate(significant_cluster = ifelse((sample_in_trial_n >= d2a[1,1] & sample_in_trial_n <= d2a[1,2]),"sig","ns"))

p2a <- ggplot(df.pupil_summary_outcome_collapse_r%>%
         filter(sample_in_trial_t <= 20, sample_in_trial_t >0), aes(x = sample_in_trial_t,
                       y = mean))+
  geom_point(aes(color = significant_cluster),
             size = 0.5)+
  geom_ribbon(aes(x = sample_in_trial_t,
                  ymin = lower, 
                  ymax = upper), 
              alpha = 0.2)+
  scale_color_viridis_d()+
  annotate("rect", xmin =0.1, xmax = 2, ymin = -1.5, ymax = 1.5,
           alpha = .2, color = "lightseagreen", fill = NA)+
  annotate("text", x = 1,y = 1.2, label = "c",
          color = "lightseagreen")+
  annotate("rect", xmin =2.1, xmax = 4, ymin = -1.5, ymax = 1.5,
           alpha = .2, color = "lightskyblue1", fill = NA)+
  annotate("text", x = 3,y = 1.2, label = "f",
          color = "lightskyblue1")+
  annotate("rect", xmin = 4.1, xmax = 6, ymin = -1.5, ymax = 1.5,
           alpha = .2, color = "lightskyblue3", fill = NA)+
  annotate("text", x = 5,y = 1.2, label = "t",
          color = "lightskyblue3")+
  annotate("rect", xmin = 6.1, xmax = 8, ymin = -1.5, ymax = 1.5,
           alpha = .2, color = "lightskyblue4", fill = NA)+
  # annotate("rect", xmin = 9.5, xmax = 11.5, ymin = -0.5, ymax = 0.5,
  #          color = "red", fill = "red", alpha = 0.1)+
  annotate("text", x = 7,y = 1.2, label = "o",
          color = "lightskyblue4")+
  labs(title = "Outcome probe",
       subtitle = "significant cluster overlayed on raw pupil",
       x = "time (s)",
       y = "z-scored pupil size")+
  theme(legend.position = "none")+
  geom_segment(aes(x = 12, y = 1, xend = 12, yend = 0.7),
                  arrow = arrow(length = unit(0.03, "npc")))+
  annotate("text",x = 12,y=1.2,label = "arousal report")

p2a
```

```{r}
p1a+p2a
ggsave("../../../VRMID-analysis/figures/study3_cluster_clean.png",width = 10, height = 5, units = "in",dpi = 300)
```
# get pupil time course for regression

## approach 1: concurrent continous bold and pupillometry (downsample to TR = 2 sec)
```{r}
df.pupil.for.regs <- df.pupil%>%
  mutate(tr = floor((Time_sec+2)/2))  %>% 
  filter(tr > 0)%>% 
  group_by(subject,block,trial,probe,rating_type,
           tr)%>%
  summarise(mean_pupil_nobc_scaled= mean(pupilDiameter_scaled, na.rm = T))

df.1sub <- read_csv("../timecourses/data/realsubj/MIDaffemo/timecourses_b0_woOutliers_long.csv") %>% 
  filter(subject == "nq240330", voi == "nacc") %>% 
  select(trial,trial_tr,tr,run) %>% 
  filter(tr <= trial_tr)

end_run1 <- df.1sub %>%
  subset(trial == 24) %>%
  .[1:5,] %>%
  mutate(tr = tr + 10)

# create the 5 TRs at the tail of run 2
end_run2 <- df.1sub %>%
        filter(run == "run-02")%>%
        subset(trial == 24) %>%
        .[1:5,] %>%
        mutate(tr = tr + 9)

# create the 5 TRs at the tail of run 3
end_run3 <- df.1sub %>%
        filter(run == "run-03")%>%
        subset(trial == 24) %>%
        .[1:5,] %>%
        mutate(tr = tr + 10)

# create the 5 TRs at the tail of run 4
end_run4 <- df.1sub %>%
        filter(run == "run-04")%>%
        subset(trial == 24) %>%
        .[1:5,] %>%
        mutate(tr = tr + 11)

df.1sub <- df.1sub %>%
        # insert 5 rows at the end of each run
        add_row(end_run1, .after = 240) %>%
        add_row(end_run2, .after = 485) %>%
        add_row(end_run3, .after = 730) %>%
        add_row(end_run4, .after = 975)
      
df.1sub <- df.1sub %>% 
  mutate(block = as.numeric(substr(run,6,6))) %>% 
  mutate(trial = trial + (block - 1) * 24) %>% 
  select(-block,-run)

for (sub in unique(df.pupil.for.regs$subject)){
  if(!is.na(sub)){
    df.pupil.for.regs_ <- left_join(df.1sub,df.pupil.for.regs %>% 
                                      filter(subject == sub),
          by = c("trial","tr")) %>% 
  relocate(subject)
    
    # # #linear interpolation
    # int <- zoo::na.approx(df.pupil.for.regs_$mean_pupil_nobc_scaled)
    # df.pupil.for.regs_$mean_pupil_nobc_scaled_i <- NA
    # df.pupil.for.regs_$mean_pupil_nobc_scaled_i[1:length(int)] <-int
    df.pupil.for.regs_$mean_pupil_nobc_scaled[is.na(df.pupil.for.regs_$mean_pupil_nobc_scaled)] <- 0
    write_delim(data.frame(df.pupil.for.regs_$mean_pupil_nobc_scaled),
                paste0("./glm_pupil_regs/",sub,"_scaled_pca.1D"), col_names = F)
    
  }
}

write_delim(data.frame(unique(df.pupil.for.regs$subject)),
            "subjects-pupil-fmri.txt", col_names = F)
```


## approach 2: lagged pupillometry (1.5 s)
```{r}
df.pupil.for.regs2 <- df.pupil%>%
  mutate(pupil_window = ifelse(sample_in_trial_t <= anticipation_window[2] & 
                                        sample_in_trial_t > anticipation_window[1],
                                      "ant",NA))%>%
  filter(pupil_window %in% c("ant"))%>% 
  group_by(subject,block,trial,probe,pupil_window)%>%
  summarise(mean_pupil_nobc_scaled= mean(pupilDiameter_scaled, na.rm = T)) %>% 
  mutate(tr = ifelse(pupil_window == "ant", 2, NA))

df.1sub <- read_csv("../timecourses/data/realsubj/MIDaffemo/timecourses_b0_woOutliers_long.csv") %>% 
  filter(subject == "nq240330", voi == "nacc") %>% 
  select(trial,trial_tr,tr,run) %>% 
  filter(tr <= trial_tr)

end_run1 <- df.1sub %>%
  subset(trial == 24) %>%
  .[1:5,] %>%
  mutate(tr = tr + 10)

# create the 5 TRs at the tail of run 2
end_run2 <- df.1sub %>%
        filter(run == "run-02")%>%
        subset(trial == 24) %>%
        .[1:5,] %>%
        mutate(tr = tr + 9)

# create the 5 TRs at the tail of run 3
end_run3 <- df.1sub %>%
        filter(run == "run-03")%>%
        subset(trial == 24) %>%
        .[1:5,] %>%
        mutate(tr = tr + 10)

# create the 5 TRs at the tail of run 4
end_run4 <- df.1sub %>%
        filter(run == "run-04")%>%
        subset(trial == 24) %>%
        .[1:5,] %>%
        mutate(tr = tr + 11)

df.1sub <- df.1sub %>%
        # insert 5 rows at the end of each run
        add_row(end_run1, .after = 240) %>%
        add_row(end_run2, .after = 485) %>%
        add_row(end_run3, .after = 730) %>%
        add_row(end_run4, .after = 975)
      
df.1sub <- df.1sub %>% 
  mutate(block = as.numeric(substr(run,6,6))) %>% 
  mutate(trial = trial + (block - 1) * 24) %>% 
  select(-block,-run)

for (sub in unique(df.pupil.for.regs2$subject)){
  if(!is.na(sub)){
    df.pupil.for.regs_ <- left_join(df.1sub,df.pupil.for.regs2 %>% 
                                      filter(subject == sub) %>% 
                                      select(subject,trial,tr,mean_pupil_nobc_scaled),
          by = c("trial","tr")) %>% 
  relocate(subject)
    
    # #linear interpolation
    # df.pupil.for.regs_$mean_pupil_nobc_scaled_i <- zoo::na.approx(df.pupil.for.regs_$mean_pupil_nobc_scaled)
    # df.pupil.for.regs_$mean_pupil_i <- zoo::na.approx(df.pupil.for.regs_$mean_pupil)
    
    df.pupil.fixation <- df.pupil.for.regs_ %>% 
      mutate(mean_pupil_nobc_scaled = ifelse(tr == 2, mean_pupil_nobc_scaled, 0)) %>% 
      mutate(mean_pupil_nobc_scaled = ifelse(is.na(mean_pupil_nobc_scaled),0,mean_pupil_nobc_scaled))
    
    write_delim(data.frame(df.pupil.fixation$mean_pupil_nobc_scaled),
                paste0("./glm_pupil_regs/",sub,"_fix_scaled_pca_lag.1D"), col_names = F)
    
  }
}
```
